-- KAHLO CAFÉ — Initialisation PostgreSQL
-- Ce fichier est conservé pour compatibilité mais n'est plus nécessaire.
--
-- Le schéma est géré par Alembic (alembic upgrade head).
-- Les données initiales sont insérées par FastAPI au démarrage (_seed_data).
-- Les index sont créés dans la migration initiale.
--
-- Pour une base vierge :
--   docker compose up --build
--   → Alembic crée le schéma
--   → FastAPI insère les fournisseurs et l'admin initial
